version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: generate example - class
          command: node bin/cli.production test/fixtures/class/index.ts -o /tmp/result/fixture-class.json
      - run:
          name: generate example - functions
          command: node bin/cli.production test/fixtures/functions/index.ts -o /tmp/result/fixture-functions.json
      - run:
          name: generate example - generics
          command: node bin/cli.production test/fixtures/generics/index.ts -o /tmp/result/fixture-generics.json
      - run:
          name: generate example - multiple-declarations
          command: node bin/cli.production test/fixtures/multiple-declarations/index.ts -o /tmp/result/fixture-multiple-declarations.json
      - run:
          name: generate example - namespace
          command: node bin/cli.production test/fixtures/namespace/index.ts -o /tmp/result/fixture-namespace.json
      - run:
          name: generate example - object
          command: node bin/cli.production test/fixtures/object/index.ts -o /tmp/result/fixture-object.json
      - run:
          name: generate example - type-alias
          command: node bin/cli.production test/fixtures/type-alias/index.ts -o /tmp/result/fixture-type-alias.json
      - run:
          name: generate example - integrated
          command: node bin/cli.production test/fixtures/integrated/index.ts -o /tmp/result/fixture-integrated.json
      - run:
          name: generate example - self
          command: node bin/cli.production src/index.ts -o /tmp/result/self.json
      - run:
          name: generate example - redux
          command: node bin/cli.production node_modules/redux/index.d.ts -o /tmp/result/redux.json
      - store_artifacts:
          path: /tmp/result
          prefix: result
