version: 2
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: generate html
          command: yarn generate test/fixture/index.ts --html /tmp/result
      - run:
          name: generate json
          command: yarn generate test/fixture/index.ts --json /tmp/result/documentation.json
      - store_artifacts:
          path: /tmp/result
          prefix: result
